exports.CreatePaymentView = require('./CreatePaymentView/CreatePaymentView')
exports.MainView = require('./Main/MainView')
exports.BankOnboarding = require('./BankOnboarding/BankOnboardingView')
exports.PaymentOnboardingView = require('./PaymentOnboarding/PaymentOnboardingView')
exports.FirstPaymentView = require('./FirstPayment/FirstPaymentView')
