const db = {
  payments: {
    incoming: [
      {
        amount: "12",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "10",
        paymentsMade: "4",
        purpose: "Hulu+",
        sender_name: "Brady Sheridan",
        sender_pic: "https://scontent-ord1-1.xx.fbcdn.net/t31.0-8/13119959_1107390755948052_7502054529648141346_o.jpg",
        sectionTitle: "Active (6)",
      },
      {
        amount: "28",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "8",
        purpose: "Goods & Services",
        sender_name: "Eric Smith",
        sender_pic: "",
        sectionTitle: "Active (6)",
      },
      {
        amount: "15",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "20",
        paymentsMade: "9",
        purpose: "I'm ugly",
        sender_name: "Mohsin Khan",
        sender_pic: "",
        sectionTitle: "Active (6)",
      },
      {
        amount: "90",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "9",
        paymentsMade: "7",
        purpose: "Ransom money",
        sender_name: "Ron Johnson",
        sender_pic: "http://www.veteranstoday.com/wp-content/uploads/2010/07/Wisconsin-U.S.-Senate-Candidate-Ron-Johnson.jpg",
        sectionTitle: "Active (6)",
      },
      {
        amount: "823",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "3",
        purpose: "Private jet rental",
        sender_name: "The Rock",
        sender_pic: "http://shop.wwe.com/on/demandware.static/-/Sites/default/dw29757933/images/slot/landing/superstar-landing/Superstar-Category_Superstar_562x408_theRock.png",
        sectionTitle: "Active (6)",
      },
      {
        amount: "49",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "3",
        purpose: "Wifi",
        sender_name: "Raucos Fella",
        sender_pic: "",
        sectionTitle: "Active (6)",
      },
    ],
    outgoing: [
      {
        amount: "388",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "11",
        purpose: "Rent!",
        sender_name: "Donna Johnson",
        sender_pic: "",
        sectionTitle: "Active (2)",
      },
      {
        amount: "5",
        confirmed: true,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "6",
        purpose: "Toilet paper subscription",
        sender_name: "Young Thug",
        sender_pic: "http://static.highsnobiety.com/wp-content/uploads/2016/02/17205911/young-thug-gq-march-2016-01.jpg",
        sectionTitle: "Active (2)",
      },
    ],
  }
};

export default db;
