import moment from 'moment';

const db = {
  payments: {
    incoming: [
      // Active incoming
      {
        amount: "12",
        confirmed: true,
        invite: false,
        nextPayment: 1473799163136,
        payments: "10",
        paymentsMade: "4",
        purpose: "Hulu+",
        sender_name: "Your Changeling",
        sender_pic: "https://scontent-ord1-1.xx.fbcdn.net/t31.0-8/13119959_1107390755948052_7502054529648141346_o.jpg",
        recip_name: "Brady Sheridan",
        recip_pic: "",
        flow: "incoming",
      },
      // Pending confirmation incoming
      {
        amount: "12",
        confirmed: false,
        invite: false,
        nextPayment: "tbd",
        payments: "9",
        paymentsMade: "0",
        purpose: "Netflix",
        sender_name: "John Doe",
        sender_pic: "",
        recip_name: "Brady Sheridan",
        recip_pic: "",
        flow: "incoming",
      },
      // Pending sender funding source incoming
      {
        amount: "13",
        confirmed: true,
        invite: false,
        nextPayment: "waiting_on_sender_fs",
        payments: "17",
        paymentsMade: "0",
        purpose: "TP!",
        sender_name: "Jim Bob",
        sender_pic: "",
        recip_name: "Brady Sheridan",
        recip_pic: "",
        flow: "incoming",
      },
      // Pending recip funding source incoming
      {
        amount: "4",
        confirmed: true,
        invite: false,
        nextPayment: "waiting_on_recip_fs",
        payments: "14",
        paymentsMade: "5",
        purpose: "Spotify Family Plan",
        sender_name: "Dad",
        sender_pic: "",
        recip_name: "Brady Sheridan",
        recip_pic: "",
        flow: "incoming",
      },
      // Pending invite incoming
      {
        amount: "41",
        confirmed: false,
        invite: true,
        nextPayment: "tbd",
        payments: "14",
        paymentsMade: "0",
        purpose: "Join dee app!",
        sender_name: "Raucos Fella",
        sender_pic: "",
        recip_name: "Brady Sheridan",
        recip_pic: "",
        flow: "incoming",
      },
    ],
    outgoing: [
      // Active outgoing
      {
        amount: "388",
        confirmed: false,
        invite: false,
        nextPayment: 1473799163136,
        payments: "12",
        paymentsMade: "9",
        purpose: "Rent",
        recip_name: "Street Youth",
        recip_pic: "",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        flow: "outgoing",
      },
      // Pending confirmation outgoing
      {
        amount: "193",
        confirmed: false,
        invite: false,
        nextPayment: "tbd",
        payments: "10",
        paymentsMade: "0",
        purpose: "Lookin' good as your dad on a friday",
        recip_name: "Young Thug",
        recip_pic: "http://static.highsnobiety.com/wp-content/uploads/2016/02/17205911/young-thug-gq-march-2016-01.jpg",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        flow: "outgoing",
      },
      // Pending confirmation outgoing
      {
        amount: "94",
        confirmed: false,
        invite: false,
        nextPayment: "tbd",
        payments: "43",
        paymentsMade: "0",
        purpose: "Some stuff",
        recip_name: "Justin Vermin",
        recip_pic: "",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        flow: "outgoing",
      },
      // Pending sender funding source outgoing
      {
        amount: "8",
        confirmed: true,
        invite: false,
        nextPayment: "waiting_on_sender_fs",
        payments: "17",
        paymentsMade: "3",
        purpose: "Some stuff",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        recip_name: "Randy Savage",
        recip_pic: "",
        flow: "outgoing",
      },
      // Pending recip funding source outgoing
      {
        amount: "4",
        confirmed: true,
        invite: false,
        nextPayment: "waiting_on_recip_fs",
        payments: "25",
        paymentsMade: "9",
        purpose: "Goods & Services",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        recip_name: "Tom Hanks",
        recip_pic: "",
        flow: "outgoing",
      },
      // Pending invite outgoing
      {
        amount: "41",
        confirmed: false,
        invite: true,
        nextPayment: "tbd",
        payments: "12",
        paymentsMade: "0",
        purpose: "Join me app!",
        sender_name: "Brady Sheridan",
        sender_pic: "",
        recip_name: "Tom Cruise",
        recip_pic: "",
        flow: "outgoing",
      },
    ],
  }
};

export default db;
