exports.MyProfile = require('./MyProfile')
exports.Notifications = require('./Notifications')
exports.BankAccounts = require('./BankAccounts')
exports.Invite = require('./Invite')
exports.Settings = require('./Settings')
